### ISSUE TITLE
SSLPeerUnverifiedException

### ISSUE THREAD

**Issue by Bachn1989** [windy1/google-places-api-java#27] opened 2015-04-16 23:28 UTC
I get the following error
```
Exception in thread "main" se.walkercrou.places.exception.GooglePlacesException: java.io.IOException: javax.net.ssl.SSLPeerUnverifiedException: Host name 'maps.googleapis.com' does not match the certificate subject provided by the peer (CN=*.storage.googleapis.com, O=Google Inc, L=Mountain View, ST=California, C=US)
```

with the following invocation

```
GooglePlaces client = new GooglePlaces(googleApiKey);                   
List<Prediction> predictions = client.getPlacePredictions(location);
```

If I manually do a HTTPS connection, I encounter no problems. I'd appreciate any suggestions you have.

**Comment by windy1** [comment] 2015-04-17 17:47
@Bachn1989 Are you working with Android? If so, could you provide your gradle file please?

**Comment by Bachn1989** [comment] 2015-04-22 06:58
@windy1 I am not working with Android.

**Comment by windy1** [comment] 2015-05-01 13:54
@Bachn1989 I've been unable to reproduce this, can you give me a little more information on what you are trying to do in what environment?

**Comment by mvaneggermond** [comment] 2015-06-11 07:23
Just had the same issue; for me it was the result of a conflict with imports. Another Maven dependency (htmlunit) was pulling in Apache HTTP Client 4.4.x. Removing HTTP Client from the dependencies resolved the error.

**Comment by windy1** [comment] 2015-07-12 01:49
Closing this now as it appears to be an issue external to this project.

**Closed by windy1** 2015-07-12 01:49 UTC
