### ISSUE TITLE
'ParseException: bad class file magic' with 2.0.1 in android gradle based project

### ISSUE THREAD

**Issue by gbero** [windy1/google-places-api-java#18] opened 2015-02-11 15:28 UTC
I'm having a lot of trouble to manage dependencies with this library. 
Do you guys have any tips for importing the library on Android ?

I can't import the 2.0.1 library in my project. 
Using version 2.0.0 or 1.2.8 building is working fine. 

This is probably a dependency problem but I can't resolve it.

While building I receive the following error.

```
Error:Execution failed for task ':xxxxxx:dexSnapshotDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/xxxxxx/android-sdk/sdk/build-tools/21.1.2/dx --dex --output /Users/xxxxxx/build/intermediates/dex/snapshot/debug --input-list=/Users/xxxxxx/build/intermediates/tmp/dex/snapshot/debug/inputList.txt
  Error Code:
  	1
  Output:
  	warning: Ignoring InnerClasses attribute for an anonymous inner class
  	(edu.emory.mathcs.backport.java.util.AbstractMap$1) that doesn't come with an
  	associated EnclosingMethod attribute. This class was probably produced by a
  	compiler that did not target the modern .class file format. The recommended
  	solution is to recompile the class from source, using an up-to-date compiler
  	and without specifying any "-target" type options. The consequence of ignoring
  	this warning is that reflective operations on this class will incorrectly
  	indicate that it is *not* an inner class.
  	warning: Ignoring InnerClasses attribute for an anonymous inner class
  	(edu.emory.mathcs.backport.java.util.AbstractMap$2) that doesn't come with an
  	associated EnclosingMethod attribute. This class was probably produced by a
  	compiler that did not target the modern .class file format. The recommended
  	solution is to recompile the class from source, using an up-to-date compiler
  	and without specifying any "-target" type options. The consequence of ignoring
  	this warning is that reflective operations on this class will incorrectly
  	indicate that it is *not* an inner class.
  	warning: Ignoring InnerClasses attribute for an anonymous inner class
  	(edu.emory.mathcs.backport.java.util.concurrent.helpers.Utils$1) that doesn't come with an
  	associated EnclosingMethod attribute. This class was probably produced by a
  	compiler that did not target the modern .class file format. The recommended
  	solution is to recompile the class from source, using an up-to-date compiler
  	and without specifying any "-target" type options. The consequence of ignoring
  	this warning is that reflective operations on this class will incorrectly
  	indicate that it is *not* an inner class.
  	warning: Ignoring InnerClasses attribute for an anonymous inner class
  	(edu.emory.mathcs.backport.java.util.concurrent.helpers.Utils$2) that doesn't come with an
  	associated EnclosingMethod attribute. This class was probably produced by a
  	compiler that did not target the modern .class file format. The recommended
  	solution is to recompile the class from source, using an up-to-date compiler
  	and without specifying any "-target" type options. The consequence of ignoring
  	this warning is that reflective operations on this class will incorrectly
  	indicate that it is *not* an inner class.
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
  		at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
  		at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
  		at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
  		at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
  		at com.android.dx.command.dexer.Main.processClass(Main.java:704)
  		at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
  		at com.android.dx.command.dexer.Main.access$300(Main.java:83)
  		at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
  		at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
  		at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
  		at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
  		at com.android.dx.command.dexer.Main.processOne(Main.java:632)
  		at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
  	...while parsing org/json/JSONArray.class
  	1 error; aborting

```

**Comment by windy1** [comment] 2015-02-11 17:12
Hey, thanks for the question! This library is available as both a maven dependency and as a standalone JAR.

If you're using Maven:

```xml
<dependencies>
    <dependency>
        <groupId>se.walkercrou</groupId>
        <artifactId>google-places-api-java</groupId>
        <version>2.0.2</version>
    </dependency>
</dependency>
```

Gradle:

```java
apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    compile group: 'se.walkercrou', name: 'google-places-api-java', version: '2.0.1'
}
```

Or just add the latest standalone (original-google-places-api.jar) to your project from [releases](https://github.com/windy1/google-places-api-java/releases)

**Comment by gbero** [comment] 2015-02-11 17:15
Yeah that's exactly what I've done. 

 compile('se.walkercrou:google-places-api-java:2.0.1') {
    exclude group: 'junit'
  }

But it seems that there are problems with the httpclient from apache common...

**Comment by windy1** [comment] 2015-02-12 03:39
Could you paste your entire `build.gradle` file please? I just fired up Android Studio and created a new gradle project and I'm unable to reproduce this issue. As far as I can tell `compile()` isn't a valid Gradle method so maybe that's the problem? Try adding the dependency in `dependencies { ... }`.

**Comment by gbero** [comment] 2015-02-12 11:21
The issue seems to be related to Java8. 
Is it possible the library has been compiled against java 8 ?

**Comment by windy1** [comment] 2015-02-12 13:33
Nope the library is compiled to Java 7. I'm closing this now as I can't help you until you give me more information like your `build.gradle` file. Thanks.

**Closed by windy1** 2015-02-12 13:33 UTC

**Comment by gbero** [comment] 2015-02-12 13:51
Well, the error displayed is : 
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)

Version 0034 = Java 8
I don't see why providing my other dependencies would help. It seems that something in the dependencies of version 2.0.1 is compiled in Java 8. I don't have any trouble when using version 1.2.8 of the library.

**Comment by intrications** [comment] 2015-02-12 13:51
@windy1 Here's a sample project that won't compile properly for me:

https://github.com/intrications/google-places-api-java-android-studio

**Comment by intrications** [comment] 2015-02-12 13:54
One strange thing that happens is that Android Studio still tries to install the APK on the device. This is not normal. Usually, if the build fails then everything stops.

**Comment by intrications** [comment] 2015-02-12 13:58
I am compiling with JDK 1.8 on OS X. @windy1 What are you using?

What is the difference between original-google-places-api-java.jar and google-places-api-java.jar?

**Comment by intrications** [comment] 2015-02-12 14:03
Here's the full output of "./gradlew assembleDebug":

http://pastebin.com/fefSK7u1

It gives more information especially:

`Error processing /Users/michael/.gradle/caches/modules-2/files-2.1/se.walkercrou/google-places-api-java/2.0.1/8f335c3ac22050f4c97978de826c4caef00964fe/google-places-api-java-2.0.1.jar:org/json/CDL.class: broken class file?`

**Comment by windy1** [comment] 2015-02-12 19:38
Okay @gbero and @intrications, after investigating the issue further I was able to reproduce the error and I found that I have been deploying shaded JARs to Maven Central which I believe was the cause for the issues you guys were experiencing. This should be fixed as of 961172ed7c07650177a0c43d5abee669be1ff57e and v2.0.4 should be available on Maven Central shortly.

@intrications To answer your question, I have also been compiling with 1.8 so I don't think that had anything to do with it since I have now been able to successfully run `./gradlew assembleDebug`.

Thank you for your guys patience.

**Comment by gbero** [comment] 2015-02-13 10:12
Nice job, thanks @windy1 ! 

I'm receiving a java.lang.NoClassDefFoundError: org.apache.http.impl.client.HttpClientBuilder when running. 

Proguard is activated but I have 
-dontwarn org.apache.http.**
-keep class org.apache.http.** { *; }

I even tried to manually add the dependency : 
compile('org.apache.httpcomponents:httpclient:4.3.5')

Do you have any idea what might cause this ?

Might be cool if we could provide our own httpclient rather than having to use httpclient from apache ?

**Comment by gbero** [comment] 2015-02-13 10:25
Ok, got it, HttpClientBuilder isn't available on Android dependencies
http://stackoverflow.com/a/27742609/1532108

adding following dependency should be fine :
compile group: 'org.apache.httpcomponents' , name: 'httpclient-android' , version: '4.3.5.1'

**Comment by windy1** [comment] 2015-02-23 04:19
Added in 791791fa12ea00cd605e34a8c36a80f06f3f3e23, thanks @gbero. :+1:
